.PHONY: clean All

All:
	@echo "----------Building project:[ Variables - Debug ]----------"
	@$(MAKE) -f  "Variables.mk"
clean:
	@echo "----------Cleaning project:[ Variables - Debug ]----------"
	@$(MAKE) -f  "Variables.mk" clean
