.PHONY: clean All

All:
	@echo "----------Building project:[ AreaCalculator - Debug ]----------"
	@$(MAKE) -f  "AreaCalculator.mk"
clean:
	@echo "----------Cleaning project:[ AreaCalculator - Debug ]----------"
	@$(MAKE) -f  "AreaCalculator.mk" clean
